version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image:
      juannazarevich/app-latest:latest
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/challengedb
      - REDIS_URL=redis
    env_file:
      - src/main/resources/application.properties
    ports:
      - 8080:8080
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=challengedb
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=challengedb_user
  redis:
    image: redis:latest
    container_name: redis